format = """
$directory\
$git_branch\
$git_status\
$line_break\
$shell\
$character
"""

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[nix_shell]
symbol = '[](cyan)'
format = '$symbol  [$name]($style) '

[python]
symbol = '[](yellow)'
format = '($symbol  [$virtualenv](blue) )'
